### PR TITLE
add travis-ci configuration

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
requires #205

**Comment by MartinNowak** [comment]
For an intro, have a look at http://docs.travis-ci.com/user/languages/d/.

**Comment by SerialVelocity** [comment]
And also, this would be great to merge.
For me, isn't because of travis-ci, but for the git submodules issue. I can't currently do:
```bash
$ dub fetch dscanner
$ dub run dscanner
```

**Comment by MartinNowak** [comment]
Updated

**Pull request merged**
